/***********************************************************************************************************
 * Module:Ultrasonic
 *
 * File Name:ultrasonic.h
 *
 * Description:Header file for ultrasonic driver
 *
 *      Author: Doha Eid
 **********************************************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include"std_types.h"
/***********************************************************************************************************
 *                                          Definitions                                                    *
 **********************************************************************************************************/
#define TRIGGER_PORT_ID           PORTB_ID
#define TRIGGER_PIN_ID            PIN5_ID
#define ECHO_PORT_ID              PORTD_ID
#define ECHO_PIN_ID               PIN6_ID

/***********************************************************************************************************
 *                                       Function Prototypes                                               *
 ***********************************************************************************************************/
/*
 * Description:
 * Function initialize ultrasonic sensor
 * Initialize the ICU driver
 * Set ICU callback function
 */
void Ultrasonic_Init(void);
/*
 *Description:
 *Function to send the trigger pulse to ultrasonic
 */
void Ultrasonic_Trigger(void);
/*
 * Description:
 * Send trigger pulse by using ultrasonic-trigger
 * Start the measurements by the ICU driver from this moment
 */
uint16 Ultrasonic_readDistance(void);
/*
 * Description:
 * This is call-back function called by ICU driver
 * This is used to calculate the high time generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
