/***********************************************************************************************************
 * Module :ultrasonic
 *
 *File Name :ultrasonic.c
 *
 *  Description:Source file for ultrasonic driver
 *
 *      Author: Doha Eid
 **********************************************************************************************************/
#include"ultrasonic.h"
#include"icu.h"
#include"common_macros.h"
#include"gpio.h"
#include<util/delay.h>
/***********************************************************************************************************
 *                                     Global Variables                                                    *
 **********************************************************************************************************/
    uint8 g_edgeCount = 0;
	uint16 g_timeHigh = 0;
/***********************************************************************************************************
 *                                   Function Decelerations                                                *
 **********************************************************************************************************/
/*
 * Description:
 * Function initialize ultrasonic sensor
 * Initialize the ICU driver
 * Set ICU callback function
 */
void Ultrasonic_Init(void)
{
	/*Create configuration structure for ICU driver
	 *ICU configure with frequency F_CPU/8
	 *ICU configure to detect the rising edge as the first edge
	 */
	 Icu_ConfigType Icu_config={F_CPU_8,RISING};
	/*Initialize the ICU */
	 Icu_init(&Icu_config);
   /*Setup the ICU call-back function*/
	 Icu_setCallBack(Ultrasonic_edgeProcessing);
   /*Setup trigger pin as output pi by gpio driver*/
    GPIO_setupPinDirection(TRIGGER_PORT_ID,TRIGGER_PIN_ID,PIN_OUTPUT);
}
/*
 *Description:
 *Function to send the trigger pulse to ultrasonic
 */
void Ultrasonic_Trigger(void)
{
	/*Give 10us trigger pulse on trigger pin to ultrasonic sensor */
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(10);/*wait 10 micro-seconds*/
	/*Stop the trigger pulse */
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_LOW);
}
/*
 * Description:
 * Send trigger pulse by using ultrasonic-trigger
 * Start the measurements by the ICU driver from this moment
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 Measured_Distance;
	/*send trigger pulse by using Ultrasonic_Trigger function*/
	Ultrasonic_Trigger();
	/*calculate the distance by timer value */
	Measured_Distance=((g_timeHigh)/58.8);

	return Measured_Distance;
}
/*
 * Description:
 * This is call-back function called by ICU driver
 * This is used to calculate the high time generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void)
{

	g_edgeCount++;
		if(g_edgeCount == 1)
		{
			/*
			 * Clear the timer counter register to start measurements from the
			 * first detected rising edge
			 */
			Icu_clearTimerValue();
			/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
		}
		else if(g_edgeCount == 2)
		{
			/* Store the High time value */
			g_timeHigh = Icu_getInputCaptureValue();
			/* Detect rising edge */
			Icu_setEdgeDetectionType(RISING);
		}
}
